### ISSUE TITLE
Editing The Blade File is mandatory

### ISSUE THREAD

**Issue by umutphp** [EdanurOzdmr/quote#1]
> Don't forget to add the {{$quotes}} code where you want to display the quote on your relevant web page!

Regarding the documentation you prepared, we have to add `{{$quotes}}` to every blade that represents a page. Is it possible to refactor it so that we do not have to add anything to the blade files?

PS: We can first discuss here if you need?

**Comment by EdanurOzdmr** [comment]
Hi @umutphp 
First of all, thank you very much for your feedback. I've been doing research on the issue and haven't found a solution yet. How can I path go about solving this issue?

**Comment by umutphp** [comment]
Hi @EdanurOzdmr ,

A Laravel application can have a layout covering the blade files. So, you can create a blade component that can be used in layout file just after the main content section.

In the blade component, you can find which page it is and get the quotes accordingly.

PS: You can ping me whenever you need via email or mentioning here.

**Comment by EdanurOzdmr** [comment]
I understand. I continue to work on the subject. I will update the package as soon as possible.

Thank you very much for your support.

> Hi @EdanurOzdmr ,
> 
> A Laravel application can have a layout covering the blade files. So, you can create a blade component that can be used in layout file just after the main content section.
> 
> In the blade component, you can find which page it is and get the quotes accordingly.
> 
> PS: You can ping me whenever you need via email or mentioning here.

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,
I updated the task by using blade component. I hope I did as you expected.

**Comment by umutphp** [comment]
Hi @EdanurOzdmr ,

I have added the component as described in the README. But I am getting the following error.

![Screenshot from 2022-09-26 10-47-09](https://user-images.githubusercontent.com/3245166/192221994-74ac3abd-a50f-4c17-a4a0-c14cf9337314.png)

I think the problem is on the following line:

https://github.com/EdanurOzdmr/quote/blob/77278648aa71b3e2cf59b575c7035513693aa89e/src/QuoteServiceProvider.php#L31

**Comment by umutphp** [comment]
Hi @EdanurOzdmr ,

Additionally, auto discovery and "vendor:publish" commands are not working either. Most probably, It is because of the problem I mentioned in the former comment. I will try them too again when you fixed the problem.

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,

An error occurred due to the "/" sign in the "QuoteServiceProvider" file being reversed. I updated the package and Readme file. Can you try again?

**Comment by umutphp** [comment]
Hi @EdanurOzdmr 

Everything works fine now :).
