### ISSUE TITLE
Composer Install Is Not Working

### ISSUE THREAD

**Issue by umutphp** [EdanurOzdmr/quote#2]
Hi @EdanurOzdmr ,

Composer install is not working. I think because you do not register your package to `composer`. So, I can not install your package to a Laravel application.

If you need help, just mention me here.

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,
I forgot to save the package in "packegist.org". Sorry. I saved the package. I tried it in another project and it works. Thank you very much for your interest.

**Comment by umutphp** [comment]
Hi @EdanurOzdmr ,

Composer install works successfully now :)
