### ISSUE TITLE
Improvement Discussion

### ISSUE THREAD

**Issue by umutphp** [EdanurOzdmr/quote#3]
Hi @EdanurOzdmr ,

Can you please come up with a solution if we want to display the quotes evenly instead of displaying randomly?

PS: If you have time you can also implement your solution.

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,
I implemented the solution and updated the package. Is this exactly what you want?

**Comment by umutphp** [comment]
Hi @EdanurOzdmr ,

It was not the solution that we want. 

Let say we have 3 quotes for "contactus" page. Instead of showing a quote randomly, we want to display the quotes equally. 

We want to guarantee that every quote is displayed to users in equal number.

Lets say we had 1000 page views for "contactus" page, than every quote shoud be displayed ~333 times.

**Comment by EdanurOzdmr** [comment]
Hi @umutphp,

In this regard, I can view each quote in order according to the previous index by using session. Do you think such a method makes sense?

**Comment by umutphp** [comment]
Hi @EdanurOzdmr,

It is reasonable :). It guarantees to see the quotes evenly for a single user.

Do you have time to one more improvement?

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,

I understand, thank you. If it is convenient for you in terms of task time, I can continue to develop it. :)

**Comment by umutphp** [comment]
Yes, It is directly in terms of task time. I will create issues separately to have the discussion.
