### ISSUE TITLE
Quotes API

### ISSUE THREAD

**Issue by umutphp** [EdanurOzdmr/quote#4]
Hi @EdanurOzdmr ,

Let's say we want to get the quotes from the [Quotes API](https://api-ninjas.com/api/quotes). We will use the `quoteconfig.php` file to store categories per page.

```
<?php
return [
    'categories' => [
        'contactus' =>'age',
        'aboutus' => 'courage'
    ]
];
```

Can you please share your solution and implement if you have time?

**Comment by EdanurOzdmr** [comment]
Hi @umutphp ,

I found a solution for this issue:
1- I edited the "quote.config" file.
2- I pulled data from the API at the url you gave according to the categories in the "quote.config" file.
3- I listed the 'quote' data from the data returned from the API in my blade component.

Finally I updated the package.

**Comment by umutphp** [comment]
Hi @EdanurOzdmr,

Many thanks for the update. It works as intended :).
